# Generated by Django 4.2.6 on 2023-10-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_category_id_alter_comment_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('magic', 'Магия'), ('potion', 'Зелья'), ('weapon', 'Оружие'), ('resources', 'Ресурсы'), ('spell_masters', 'Заклинания')], on_delete=django.db.models.deletion.CASCADE, to='usersapp.category'),
        ),
    ]
