# Generated by Django 4.2.6 on 2023-10-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('magic', 'Магия'), ('potion', 'Зелья'), ('weapon', 'Оружие'), ('resources', 'Ресурсы'), ('spell_masters', 'Заклинания')], max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.category'),
        ),
    ]
